name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

      
    - name: gradle init
      run: gradle init --stacktrace

    - name: gradle test
      run: gradle test --stacktrace
